#!/bin/bash
# Example with 64 MPI tasks and 8 tasks per node.
#
# Runtime of this jobs is less then 1 hour.
#SBATCH --time=1:00:00
#
# Partition to use
#SBATCH --partition=bench
#
# Number of nodes
#SBATCH --nodes 2
#
# Number of MPI tasks
#SBATCH -n 2
#
# Number of MPI tasks per node
#SBATCH --tasks-per-node=1

module load mpi
mpic++ -Wall src/calculate_MPI_pi.cpp -o mpi_pi
mpirun ./mpi_pi 100000 2

# End of submit file

