#!/bin/bash
# Example with 64 MPI tasks and 8 tasks per node.
#
# Runtime of this jobs is less then 1 hour.
#SBATCH --time=1:00:00
#
# Partition to use
#SBATCH --partition=bench
#
# Number of nodes
#SBATCH --nodes 4
#
# Number of MPI tasks
#SBATCH -n 4
#
# Number of MPI tasks per node
#SBATCH --tasks-per-node=1

module load mpi
mpic++ -Wall src/test_send_recieve.cpp -o mpi_sr
mpirun ./mpi_sr

# End of submit file

